from typing import Dict, Any, Callable
from .idempotency_key_generator import IIdempotencyKeyGenerator
from ...constants import KEY_FUNCTION_NOT_CALLABLE

class CustomIdempotencyKeyGenerator(IIdempotencyKeyGenerator):
    """
    Custom idempotency key generator using user-provided function.
    
    This strategy allows complete control over key generation by accepting
    a custom function. The function receives args, context, and spec, and
    returns a string key.
    
    Features:
        - Complete flexibility in key generation
        - Can access any data from args, context, or spec
        - Can use external services or databases
        - Can implement complex business logic
    
    Usage:
        def my_custom_key(args, ctx, spec):
            # Custom logic here
            timestamp = args.get('timestamp', '')
            user_id = ctx.user_id or 'anonymous'
            return f"{spec.id}:{user_id}:{timestamp}"
        
        generator = CustomIdempotencyKeyGenerator(my_custom_key)
        key = generator.generate_key(args, ctx, spec)
    
    Use Cases:
        - Complex business rules for key generation
        - Integration with external ID generation services
        - Time-based keys with custom expiry logic
        - Geographic or tenant-based key partitioning
    
    Warning:
        The custom function must return deterministic keys (same inputs
        produce same output) for idempotency to work correctly.
    """
    
    def __init__(self, key_function: Callable[[Dict[str, Any], Any, Any], str]):
        """
        Initialize with custom key generation function.
        
        Args:
            key_function: Function that takes (args, ctx, spec) and returns str
        
        Raises:
            TypeError: If key_function is not callable
        """
        if not callable(key_function):
            raise TypeError(KEY_FUNCTION_NOT_CALLABLE)
        
        self.key_function = key_function
    
    def generate_key(self, args: Dict[str, Any], ctx: Any, spec: Any) -> str:
        """
        Generate idempotency key using custom function.
        
        Args:
            args: Tool execution arguments
            ctx: Tool context
            spec: Tool specification
            
        Returns:
            str: Key generated by custom function
            
        Raises:
            Exception: Any exception raised by the custom function
        """
        return self.key_function(args, ctx, spec)

